INSERT INTO stars VALUES (DEFAULT, 1), (DEFAULT, 2), (DEFAULT, 3),
(DEFAULT, 4),(DEFAULT, 5);

INSERT INTO formats VALUES (DEFAULT, 'libro'), (DEFAULT, 'E-book');

INSERT INTO categories VALUES (DEFAULT, 'Más vendidos'), (DEFAULT, 'Novedades'), 
(DEFAULT, 'Recomendados');

INSERT INTO genres VALUES (DEFAULT,'Policial'), (DEFAULT,'Histórica'),
 (DEFAULT,'Ciencia ficción'), (DEFAULT,'Romance'), (DEFAULT,'Misterio'),
 (DEFAULT,'Juvenil'),(DEFAULT,'Terror'),(DEFAULT,'Thriller'),(DEFAULT,'Fantasía');
 
 INSERT INTO editorials VALUES (DEFAULT, 'Plaza & Janés'), 
 (DEFAULT, 'B de bolsillo'), (DEFAULT, 'Granica'),
(DEFAULT, 'Suma'), (DEFAULT, 'Booket'),
(DEFAULT, 'Puck'), (DEFAULT, 'Wattpad'),
(DEFAULT, 'Ediciones Urano'), (DEFAULT, 'Penguin random house'),
(DEFAULT, 'Ediciones B'), (DEFAULT, 'Montena'),
(DEFAULT, 'Planeta'), (DEFAULT, 'Sudamericana'),(DEFAULT, 'Martínez Roca'),
(DEFAULT, 'Hidra'), (DEFAULT, 'Alianza'),
(DEFAULT, 'Ediciones Akal'), (DEFAULT, 'De Bolsillo') ;


INSERT INTO authors VALUES (DEFAULT, 'John Grisham'),
(DEFAULT, 'John Katzenbach'),
(DEFAULT,'Markus Zusak'),
(DEFAULT,'H. G. Wells'),
(DEFAULT,'Florencia Bonelli'),
(DEFAULT,'Adam Silvera'),
(DEFAULT,'Jojo Moyes'),
(DEFAULT,'Carlos Ruiz Zafón'),
(DEFAULT,'Kerri Maniscalco'),
(DEFAULT,'Godoy Ariana'),
(DEFAULT,'Elena Castillo Castro'),
(DEFAULT,'Ana Coello'),
(DEFAULT,'Stephen King'),
(DEFAULT,'Carolina Andujar'),
(DEFAULT,'Clifford D. Simak'),
(DEFAULT,'Paulo Coelho'),
(DEFAULT,'Oscar Wilde'),
(DEFAULT,'Angel David Revilla'),
(DEFAULT,'Leigh Bardugo'),
(DEFAULT,'Emily Jane Brontë'),(DEFAULT,'Arthur Conan Doyle');

INSERT INTO books (id, title, isbn, stock, price, slogan, pages, synopsis, authorId, genreId, formatId, categoryId, editorialId, starId, cover)
 VALUES (DEFAULT, 'El manuscrito',9789506445584, 100, 1500,'¡Llega la esperadísima novela del maestro de los thrillers policiales y judiciales!',
 336, 'Cuando el huracán Leo se desvía de su curso previsto para dirigirse hacia Camino Island, en la costa de Florida, la mayoría de sus habitantes decide abandonar la isla. Solo un pequeño grupo de irreductibles elige quedarse, entre ellos Bruce Cable, el propietario de la librería Bay Books. El huracán avanza destrozándolo todo y dejando casas derrumbadas, hoteles y tiendas destruidas, calles inundadas y una docena de muertos. Uno de los fallecidos es Nelson Kerr, amigo de Bruce y autor de thrillers. Pero los indicios sugieren que la tormenta no fue la causa de la muerte de Nelson: la víctima recibió numerosos golpes sospechosos en la cabeza. ¿Quién querría matar a Nelson? La policía local está sobrepasada por los efectos del huracán y no se encuentra en condiciones de ocuparse del caso. Pero Bruce comienza a preguntarse si algunos oscuros personajes de las novelas de su amigo podrían ser más reales que ficticios. Y en algún lugar del ordenador de Nelson está el manuscrito de su nueva novela. ¿Estará allí, en negro sobre blanco, la clave del caso? Bruce empieza a investigar y lo que descubre entre sus páginas es más impactante que cualquiera de los giros de las tramas de Nelson... y mucho más peligroso.',
 1,1,1,3,1,4, 'el-manuscrito.png'),
 (DEFAULT, 'El psicoanalista', 9789876278270, 150, 2100,'Novela que lanzo a la fama a John Katzenbach',
 528,'Feliz aniversario, doctor. Bienvenido al primer día de su muerte. Así comienza el anónimo que recibe el psicoanalista Frederick Starks, y que le obliga a emplear toda su astucia y rapidez para, en quince días, averiguar quién es el autor de esa amenazadora misiva que promete hacerle la vida imposible. De no conseguir su objetivo, deberá elegir entre suicidarse o ser testigo de cómo, uno tras otro, sus familiares y conocidos mueren por obra de un psicópata decidido a llevar hasta el final su sed de venganza. Dando un inesperado giro a la relación entre médico y paciente, John Katzenbach nos ofrece una novela emblemática del mejor suspense psicológico.',
 2, 1, 1, 3,2,5,'el-psicoanalista.jpg'),
 (DEFAULT, 'La ladrona de libros', 9788499088075, 98,1900, 'Una novela preciosa, tremendamente humana y emocionante, que describe las peripecias de una niña alemana de nueve años desde que es dada en adopción por su madre hasta el final de la II Guerra Mundial.',
 544, 'Érase una vez un pueblo donde las noches eran largas y la muerte contaba su propia historia. En el pueblo vivía una niña que quería leer, un hombre que tocaba el acordeón y un joven judío que escribía bellos cuentos para escapar del horror de la guerra. Al cabo de un tiempo, la niña se convirtió en una ladrona que robaba libros y regalaba palabras. Con estas palabras se escribió una historia hermosa y cruel que ahora ya es una novela inolvidable.',
 3,2,1,1,2,4,'la-ladrona-de-libros.jpg'),
 (DEFAULT, 'La guerra de los mundos',9789563164411,47,2400,'¡Obra maestra de la Ciencia Ficción!',
 256,'Publicado en 1898, La guerra de los mundos es una de las piezas fundacionales de la ciencia ficción, en donde se crea el arquetipo por excelencia de este género: la visita de seres de otros mundos con intenciones hostiles, armados con pistolas de rayos y montados en estructuras biomecánicas. H. G. Wells describe en esta novela la invasión de un ejército de marcianos y los vanos esfuerzos desplegados por los humanos para impedirla. La humanidad, con toda su soberbia y falsa seguridad se ve obligada a replantearse el lugar en el universo.',
 4,3,1,1,3,5,'la-guerra-de-los-mundos.jpg'),
 (DEFAULT, 'La tía Cósima',9789877391480,85,2000,'¿Puede el amor regalar una segunda oportunidad?',
 576,'Una historia de cómo el amor vence al odio. Cósima es una mujer en la plenitud de la vida. Psicóloga de profesión y especializada en el tratamiento del autismo infantil, posee una fundación de enorme prestigio, donde se respira un ambiente cuidado y buen humor. Allí trabaja con perros especialmente adiestrados para ayudar a los niños con alguna condición del espectro autista. En su adolescencia, sin embargo, padeció la crueldad de algunos compañeros de escuela, experiencia que la marcó profundamente, al tiempo que le sirvió para convertirse en la mujer comprometida que es hoy. Si bien esa etapa de sufrimiento quedó atrás, un día irrumpe de nuevo para ofrecerle algo que quizá deseaba: un amor inesperado, una pasión que la desborda, un abismo de sorpresa e incertidumbre. ¿Podrá ese amor reparar el daño que no se olvida? ¿Podrá deshacer la vergüenza, la frustración y el enojo?',
 5, 4, 2, 2, 4, 3,'la-tia-cosima.jpg'),
 (DEFAULT, 'Al final mueren los dos', 9789874132017,185,1500,'¿Puede un solo día albergar toda una vida?',
 352,'En un presente alternativo, en el que es posible predecir la muerte con un plazo de veinticuatro horas, Mateo Torrez y Rufus Emeterio acaban de recibir la llamada más temida: la misma que te avisa de que ha llegado tu hora final. En circunstancias normales, es poco probable que Mateo y Rufus se hubieran conocido. Pero sus circunstancias no son normales en absoluto. Porque les quedan, a lo sumo, veinticuatro horas de vida.',
 6, 4, 2, 2, 6, 3,'al-final-mueren-los-dos.png'),
 (DEFAULT, 'Yo antes de ti', 9789870434665,65,3000,'Una historia que necesitas experimentar.',
 494,'Lo que Will no sabe es que Lou está a punto de irrumpir en su mundo con una explosión de color. Y ninguno de los dos sabe que va a cambiar al otro para siempre. Yo antes de ti reúne a dos personas que no podrían tener menos en común en una novela conmovedoramente romántica con una pregunta: ¿Qué decidirías cuando hacer feliz a la persona a la que amas significa también destrozarte el corazón?',
 7,4, 1, 2,4, 4,'yo-antes-de-ti.jpg'),
 (DEFAULT, 'La sombra del viento',9789504956068, 80, 3100,'No te puedes perder esta saga, es una de las más grandes series de la novela contemporánea española',
 576, 'El Cementerio de los Libros Olvidados, el cuarteto de novelas que arranca con La Sombra del Viento y sigue con El Juego del Ángel, se ha convertido en la gran saga novelística en curso de nuestro tiempo. Un amanecer de 1945, un muchacho es conducido por su padre a un misterioso lugar oculto en el corazón de la ciudad vieja: El Cementerio de los Libros Olvidados. Allí, Daniel Sempere encuentra un libro maldito que cambia el rumbo de su vida y le arrastra a un laberinto de intrigas y secretos enterrados en el alma oscura de la ciudad. La Sombra del Viento es un misterio literario ambientado en la Barcelona de la primera mitad del siglo xx, desde los últimos esplendores del Modernismo hasta las tinieblas de la posguerra.',
 8, 5, 2, 3, 5, 5,'sombra-del-viento.jpg'),
 (DEFAULT, 'A la caza de Houdini', 9789877391480, 100, 1800,'Un asesino termina con la vida de los pasajeros uno por uno… y no hay lugar adonde escapar',
 480, 'Audrey Rose y Thomas Cresswell se encuentran a bordo de un lujoso transatlántico que se convierte en una horrorosa prisión flotante cuando un asesino termina con la vida de los pasajeros uno por uno… y no hay lugar adonde escapar. Al emprender un viaje de una semana por el océano Atlántico a bordo del opulento RMS Etruria, Audrey Rose Wadsworth y su compañero de investigaciones, Thomas Cresswell, se ven deslumbrados por una compañía itinerante de artistas de circo, videntes y un carismático joven escapista que entretienen por las noches a los pasajeros de la primera clase.',
 9, 5, 2, 3, 6, 3,'a-la-caza-de-houdini.png'),
 (DEFAULT, 'A traves de mi ventana', 9789877391480, 64,1750, 'Llega la novela fenómeno de Wattpad',
 416, 'Ares Hidalgo, mi odioso y muy muy atractivo vecino, el chico al que acoso desde las sombras, nunca había notado mi presencia (porque básicamente lo observaba desde la sombras) hasta que una serie de eventos nos llevaron a interactuar por primera vez y... el hecho es que Ares cambió mi vida. ¿Para bien? ¿O para mal? Ya veremos. Mi nombre es Raquel, y esta es la historia que comenzó A través de mi ventana.',
 10, 6, 2, 3, 7, 3,'A traves de mi ventana'),
 (DEFAULT, 'El teorema de júpiter', 9788416327652, 255, 1400, 'Una historia de amor, que va tomando retazos importantes de una vida compartida y a la vez hecha de diferentes perspectivas y que se nutre de cada sabiduría.',
 346, 'Landon Frazier no solo es el popular quarterback del equipo de fútbol de Abbeville y un estudiante ejemplar, también es el hijo del médico de este pequeño pueblo descendiente de los primeros colonos Alabama. Cuando Malia, una pequeña creek de la reserva de Atmore entra en su vida, salvaje e inocente, la llena de nuevas tonalidades que descolocarán las bases de la tradicional vida sureña de su familia, descubriendo otra forma de mirar el mundo. Nacerá una amistad que crecerá con el paso de los años, a pesar de las reticencias y circunstancias de ambas familias y de sus propios miedos, revelándose unos sentimientos imparables.',
 11, 4, 2, 2, 8, 4,'el-teorema-de-jupiter.jpg'),
 (DEFAULT, 'Luna I En la oscuridad', 9789585986619, 196, 2000, 'La primera entrega de una trilogía que promete al lector, fantasía, misterio e intriga en altas dosis...',
 396, 'Luna I en la oscuridad Por Ana Coello ,No todas las decisiones son fáciles, menos si son resultado de la culpa y el dolor. Para Sara nada volvió a ser lo mismo desde la muerte de su madre. Y como si aquello no bastara, tuvo que mudarse a una nueva ciudad, incluso a otro país. Sara ansía escapar de todo aquello que le aflige, y cuando menos se lo espera, aparecen en su nueva escuela tres alumnos desconcertantes. Uno de ellos, Luca, le genera emociones inesperadas y contradictorias, y aunque lo eviten, ambos avanzarán hacia lo desconocido..., sin imaginar que no existe marcha atrás. Con Luna, primera entrega de la trilogía En la oscuridad, Ana Coello nos sumerge en una peligrosa novela romántica, con la que busca continuar el éxito en Wattpad, gracias a millones de lecturas de todas sus historias.',
 12, 4, 2, 1, 9, 3,'en-la-oscuridad-de-la-luna.jpg'),
 (DEFAULT, 'Personas Desconocidas',9789588991269, 200,2870,'Katzenbach nos ofrece un thriller de ritmo imparable, protagonistas convincentes y trama compleja pero fascinante al mismo tiempo.', 475,
 'Una niña de trece años que desaparece sin dejar rastro. Cuatro jóvenes blancos asesinados. Dos policías retirados que no quieren o no pueden hablar. Un narcotraficante entre rejas con más información de la que debiera, y una pareja de policías empeñados en descubrir la verdad: una perfecta combinación para un thriller fenomenal, como solo John Katzenbach podría escribirlo.',
 2, 8, 2, 2, 10, 4,'Personas-desconocidas.jpg'),
 (DEFAULT, 'Desesperación', 9789877391480,74,3100,'Presenta muchas características habituales en la bibliografía del autor, como la lucha por la supervivencia, el enfrentamiento entre el bien y el mal, su naturaleza fantástica y un grupo de personajes variopintos protagonistas de la historia...',
 718, 'En la interestatal 50, en el desértico y solitario tramo que atraviesa Nevada, un gato muerto ensartado en un cartel da la bienvenida al pequeño pueblo minero de Desesperación. Allí, un policía local poseído por un perverso ser se ha erigido en autoridad suprema y sanguinaria, y elige sus víctimas entre los escasos vehículos que circulan por carretera. Aquellos que mueren rápidamente son en realidad los más afortunados, ya que para los supervivientes Desesperación se convertirá en el escenario de una horrenda pesadilla.',
 13, 7, 1, 2, 18, 5,'desesperacion.jpg'),
 (DEFAULT, 'El despertar de la sirena',9789585951099, 120, 1500, 'El mar está lleno de peligros. Algunos son conocidos para el hombre... y otros no',
 134,'Han pasado trescientos años desde la última vez que Juraté, la sirena maldita, surcó las aguas del mar Báltico. Ya es hora de que regrese a la superficie en busca de un nuevo amor...',
14, 7, 2, 2, 11, 3,'el-despertar-de-la-sirena.jpg' ),
(DEFAULT, 'Los hijos de nuestros hijos', 9789504935648, 150,1900,'Dicen que vienen del futuro. Son los hijos de nuestros hijos.',
186, 'Un día de verano como otro cualquiera, se abre una puerta en el vacío y empiezan a salir cientos, miles, millones de personas procedentes de ninguna parte. Dicen que vienen del futuro. Son los hijos de nuestros hijos. Un peligro incontrolable acecha en el futuro, y se hace preciso cortar el puente que los ha traído a través del tiempo. Pero, como suele ocurrir en estos casos, alguien se deja, una puerta abierta... y aquí empiezan los verdaderos problemas de la novela de Clifford D. Simak.',
15, 3, 1, 3, 14, 4,'los-hijos-de-nuestros-hijos.jpg'),
(DEFAULT, 'Veronica decide morir', 9789504935605, 140, 2000, 'Sueños y fantasías. Deseo y muerte. Locura y pasión',
232, 'Veronika es una joven completamente normal. Es guapa, no le faltan pretendientes y tiene un buen trabajo. Su vida transcurre sin mayores sobresaltos, sin grandes alegrías ni grandes tristezas. Pero no es feliz. Por eso, una mañana de noviembre, Veronika decide acabar con su vida. En el camino hacia la muerte, Veronika experimenta placeres nuevos y halla un nuevo sentido a la vida, un sentido que le había permanecido oculto hasta ahora, cuando tal vez sea demasiado tarde par echarse atrás. Veronika decide morir plantea que cada segundo de nuestra existencia optamos entre la alternativa de seguir adelante o de abandonar',
16, 4, 1, 3, 12, 3,'veronika-decide-morir.jpg'),
(DEFAULT, 'El retrato de Dorian Gray', 9789500755955, 200, 3200, 'Un libro lleno de fascinación y encanto, fácil y difícil a la vez, y cuyo único protagonista y tema esencial es la belleza. Una de las pasiones que hacen vivir, dan sentido y fuerza al mundo.',
256, 'Basil Hallward es un artista que queda fuertemente impresionado por la belleza estética de un joven llamado Dorian Gray y comienza a admirarlo. Basil pinta un retrato del joven. Charlando en el jardín de Hallward, Dorian conoce a un amigo de Basil y empieza a cautivarse por la visión del mundo de Lord Henry. Exponiendo un nuevo tipo de hedonismo, Lord Henry indica que «lo único que vale la pena en la vida es la belleza, y la satisfacción de los sentidos». Al darse cuenta de que un día su belleza se desvanecerá, Dorian desea tener siempre la edad de cuando Basil le pintó en el cuadro. Mientras él mantiene para siempre la misma apariencia del cuadro, la figura retratada envejece por él. Su búsqueda del placer lo lleva a una serie de actos de lujuria; pero el retrato sirve como un recordatorio de los efectos de su alma, donde el retrato llevará la carga de su envejecimiento y sus pecados.',
17, 5, 1, 3, 13, 5,'el-retrato-de-dorian-gray.jpg'),
(DEFAULT, 'Despues', 9789506445614, 100, 2600, 'Nació con una habilidad sobrenatural que su madre le insta a mantener en secreto y que le permite ver aquello que nadie puede y enterarse de lo que el resto del mundo ignora',
248, 'Jamie Conklin, el único hijo de una madre soltera, solo quiere tener una infancia normal. Sin embargo, nació con una habilidad sobrenatural que su madre le insta a mantener en secreto y que le permite ver aquello que nadie puede y enterarse de lo que el resto del mundo ignora. Cuando una inspectora del Departamento de Policía de Nueva York le obliga a evitar el último atentado de un asesino que amenaza con seguir atacando incluso desde la tumba, Jamie no tardará en descubrir que el precio que debe pagar por su poder tal vez es demasiado alto',
13, 8, 1, 3, 1, 5, 'despues.jpg'),
(DEFAULT, 'El libro negro', 9789508701534, 100, 2400, 'El universo se vuelve escalofriante cuando la vida se bifurca. Vuelve Dross con su primer libro de cuentos.', 
232, 'La vida puede ser una verdadera mierda para algunas, que no la mayoría de las personas. Sin embargo, por lo menos un par de veces, a lo largo y ancho de esa vida, ésta elige un día para demostrarnos qué tanto asco puede dar. Esto les pasa a todos y cada uno de los seres humanos que habitan en este mundo, caprichosos o no, malos o buenos, simples o excéntricos: todos tienen una probada de qué tan mal pueden salir las cosas durante veinticuatro horas.Y para mí, ese día parece que va a ser hoy.”En los cuatro cuentos reunidos en este libro escabroso, David Ángel Revilla, alias Dross, nos revela detalles perturbadores de la deep web y que la vida jamás es lo que parece y que la existencia humana no es más que un recorte fugaz y lastimoso del universo.',
18, 8, 1, 3, 14, 3, 'el-libro-negro.jpg' ),
(DEFAULT, 'Sombra y hueso', 9788418002526, 150, 2000, 'Sombra y Hueso es una aventura de fantasía, y novela de debut escrita por Leigh Bardugo.',
416,'Alina Starkov no espera mucho de la vida. Se quedó huérfana después de la guerra y lo único que tiene en el mundo es a su amigo Mal. A raíz de un ataque que recibe Mal al entrar en La Sombra, una oscuridad antinatural repleta de monstruos que ha aislado el país, Alina revela un poder latente que ni ella misma sabía que tenía. Tras ese episodio, Alina es conducida a la fuerza hasta la corte real para ser entrenada como un miembro de los Grisha, un grupo de magos de élite comandado por un individuo misterioso que se hace llamar El Oscuro.',
19, 9, 1, 2, 15, 5,'portada-1629763029228.jpg'),
(DEFAULT, 'Asedio y tormenta', 9788415709367, 140, 2500, 'Llega la esperada continuación de Sombra y hueso.',
580, 'Hay tres cosas de las que Alina jamás podrá escapar. Su pasado. Su poder. Y su destino. Alina pronto va a tener que enfrentarse a una terrible verdad. La oscuridad nunca muere.',
19, 9, 1, 2, 15, 5,'default-image.png'),
(DEFAULT, 'Ruina y ascenso', 9788415709374, 160, 2700, 'Al fin llega la conclusión de la trilogía Sombra y hueso.',
580, 'La capital ha caído. El Oscuro gobierna Ravka desde su trono de sombras.Ahora el destino de la nación está en manos de una Invocadora del Sol sin poderes, un rastreador caído en desgracia y los últimos vestigios de lo que alguna vez fue un gran ejército de magos.',
19, 9, 1, 2, 15, 5, 'portada-1629692644875.jpg'),
(DEFAULT, 'Cumbres borrascosas', 9788491819431, 194, 3100, 'Melancólico relato sobre el amor más allá de la muerte, la rivalidad entre hermanos y la venganza.',
416, 'La poderosa y hosca figura del atormentado Heathcliff domina Cumbres Borrascosas, novela apasionada y tempestuosa cuya sensibilidad se adelantó a su tiempo. Los brumosos y sombríos páramos de Yorkshire son el singular escenario donde se desarrolla con fuerza arrebatadora esta historia de venganza y odio, de pasiones desatadas y amores desesperados que van más allá de la muerte y que hacen de ella una de las obras más singulares y atractivas de todos los tiempos.',
20, 4, 1, 3, 16, 4, 'portada-1629696615473.jpg'),
(DEFAULT, 'El Sabueso de los Baskerville', 9798542961620, 190, 2200, 'Un caso que lleva al límite de lo racional el talento detectivesco de Sherlock Holmes y su infatigable compañero, el Doctor Watson.',
190, 'Un adinerado hombre de negocios es hallado muerto en las cercanías de su casa. Todo indica que su corazón se detuvo y las escasas pistas sugieren que estaba huyendo de alguien; o quizá de algo que nadie quiere nombrar: la maldición de los Baskerville, encarnada en un infernal sabueso de proporciones descomunales. Pero ya sea obra de un criminal o de una criatura fantasmal, Sherlock Holmes está dispuesto a agotar todas las hipótesis antes de admitir que el diablo ha decidido castigar a la familia Baskerville.',
1, 1, 1,  3, 17, 4, 'portada-1629776942495.jpg');